language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-native-compilers
    - opam
    - libfftw3-dev
    - liblapack-dev

script: bash -ex travis-ci.sh
env:
  - OPAM_SWITCH=4.03.0
  - OPAM_SWITCH=4.04.2
  - OPAM_SWITCH=4.05.0
  - OPAM_SWITCH=4.06.0
